<a href="https://colab.research.google.com/github/obaniah/Assignment-3-CS-4783-5783---Oday-Bani-Ahmadd/blob/main/Q3_AS_3_ML_CS_5783_ODAY_BANI_AHMAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import keras as keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten , MaxPooling2D , Dropout

Q3 . 1.  What are the dimensions of the input and the kernel (or filter)? How many parameters are there in the kernel f? 



*   Filter Dimensions (3, 3) 

*   Input Dimensions (6, 6)

*   Number of parameters in the kernel = 3*3 = 9 





 

In [ ]:
x = np.matrix('7 5 0 0 3 2; 6 4 5 1 4 8; 9 0 2 2 5 4; 6 3 4 7 9 8; 5 7 5 6 9 0; 7 9 0 8 2 3')
print(' input  ','\n',  x, '\n')
print('dimensions of the input  is   ',x.shape)



 input   
 [[7 5 0 0 3 2]
 [6 4 5 1 4 8]
 [9 0 2 2 5 4]
 [6 3 4 7 9 8]
 [5 7 5 6 9 0]
 [7 9 0 8 2 3]] 

dimensions of the input  is    (6, 6)


In [ ]:
f = np.matrix('1 0 -1; 2 0 -2; 1 0 -1')
print(' Kernel  ','\n',  f, '\n')
print('dimensions of the Kernel  is' ,f.shape)


 Kernel   
 [[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]] 

dimensions of the Kernel  is (3, 3)


In [ ]:
input_dim = x.shape
print('input Dimensions', input_dim,'\n\n')
Kernel_dim = f.shape
print('Filter Dimensions', Kernel_dim )



input Dimensions (6, 6) 


Filter Dimensions (3, 3)


Q3 - 2. What is the output activation map when you apply the convolutional operation using the filter f on the input X without padding?

In [ ]:
el_total = 0
activation_map = []

for m in range(4):
  for i in range(4):
    sub = x[m:m+3 , i : i+3]
    sub_total = 0

    #print(sub,'\n')
    sub = np.matrix(sub)
    sub_total = 0
    for k in range(3):
      for h in range(3):
        el = f[k,h]*sub[k,h]
        sub_total = el + sub_total
        #print(y_r)



    #print(el_total)
    activation_map.append(sub_total)


#print(activation_map)  
activation_map = np.asarray(activation_map)
activation_map  = np.reshape(activation_map, (4, 4)) 
activation_map = np.asmatrix(activation_map)

print('Output Activation Map','\n\n', activation_map)  


Output Activation Map 

 [[ 16   9  -4 -18]
 [ 17  -5 -10 -12]
 [ 11  -9 -17   2]
 [  9  -1 -15  16]]


Q3 - 3. What is the output when you apply a max-pooling operation on the output from the previous question?

In [ ]:
#output when you apply a max-pooling

AM = activation_map

OUT_MP =[]
for m in range(0,len(AM),2):
  for i in range(0,len(AM),2):
    MP = AM[ m : m+2 , i : i+2]
    MP = np.matrix(MP)
    max_value_MP = np.max(MP)
    #print(max_value_MP)
    OUT_MP.append(max_value_MP)





    #print(MP,'\n')


OUT_MP  = np.array(OUT_MP)
OUT_MP  = np.reshape(OUT_MP, (2, 2)) 
OUT_MP  = np.asmatrix(OUT_MP)
print('Output when you apply a max-pooling\n',OUT_MP)   






Output when you apply a max-pooling
 [[17 -4]
 [11 16]]


***test my loop***

In [ ]:
hh = np.matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 1.],
        [0., 0., 1., 0., 1., 1.],
        [0., 0., 0., 1., 1., 0.],
        [1., 0., 1., 1., 1., 0.],
        [0., 1., 0., 0., 0., 1.]])

ff = np.matrix('1 0 1; 0 1 0; 1 0 1')


el_total2 = 0
activation_map2 = []

for m in range(4):
  for i in range(4):
    sub2 = hh[m:m+3 , i : i+3]
    #print(sub,'\n')
    sub2 = np.matrix(sub2)
    sub_total = 0
    for k in range(3):
      for h in range(3):
        el2 = ff[k,h]*sub2[k,h]
        sub_total = el2 + sub_total
        #print(y_r)
        #el_total2 = el_total2 + el2
        #if h == 3 and k ==3:
        #el_total2=0  
      



    #print(sub_total)
    activation_map2.append(sub_total)


#print(activation_map)  
activation_map2 = np.asarray(activation_map2)
activation_map2  = np.reshape(activation_map2, (4, 4)) 
activation_map2 = np.asmatrix(activation_map2)

print('Output Activation Map','\n\n', activation_map2)  



Output Activation Map 

 [[3. 0. 2. 2.]
 [0. 3. 2. 3.]
 [3. 1. 5. 3.]
 [0. 3. 2. 3.]]
